name: 15-share-artifact
on:
  push:
  workflow_dispatch:
jobs:	
  jobSource:
    runs-on: ubuntu-latest
    steps:
      - name: Create File
        run: echo "hallo Welt" > ./mydata.txt
      - name: Upload File
        uses: actions/upload-artifact@v4
        with:
          name: greeting
          path: ./mydata.txt
  jobTarget:
    runs-on: ubuntu-latest
    needs: jobSource
    steps:
      - name: Download File
        uses: actions/download-artifact@v4
        with:
           name: greeting
           path: ./greeting.txt
      - run: cat ./greeting.txt
